version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-generator:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /src/project_forge/template/backend
    schedule:
      interval: weekly
    groups:
      python-template:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /src/project_forge/template/frontend
    schedule:
      interval: weekly
    groups:
      frontend-template:
        patterns: ["*"]
